### ISSUE TITLE
Securing REST APIs - broken links

### ISSUE THREAD

**Issue by isuruuy429** [wso2/docs-ei#1686]
**Description:**
Doc: https://ei.docs.wso2.com/en/7.1.0/micro-integrator/use-cases/examples/rest_api_examples/securing-rest-apis/
**Configure a read-only LDAP user store** link not found. 

Doc: https://ei.docs.wso2.com/en/7.1.0/micro-integrator/develop/advanced-development/applying-security-to-an-api/
 **configure a user store** page not found. 

link to the jar is not found. 
Doc: https://ei.docs.wso2.com/en/7.1.0/micro-integrator/develop/advanced-development/applying-security-to-an-api/
section: Using Kerberos to secure the REST API
**WSO2-REST-KerberosAuth-Handler-1.0.0-SNAPSHOT.jar**

**Comment by nilminiwso2** [comment]
First two issues are fixed:
- Doc: https://ei.docs.wso2.com/en/7.1.0/micro-integrator/use-cases/examples/rest_api_examples/securing-rest-apis/
  Configure a read-only LDAP user store link not found.
- Doc: https://ei.docs.wso2.com/en/7.1.0/micro-integrator/develop/advanced-development/applying-security-to-an-api/
   configure a user store page not found.

Regarding third issue:
- link to the jar is not found.
  Doc: https://ei.docs.wso2.com/en/7.1.0/micro-integrator/develop/advanced-development/applying-security-to-an-api/
  section: Using Kerberos to secure the REST API
   WSO2-REST-KerberosAuth-Handler-1.0.0-SNAPSHOT.jar

@Nirothipan / @sdkottegoda - According to [1], this [2] seems to be correct JAR.

[1] https://docs.google.com/document/d/1zhobe9HSXfg525xKSBIEvJP7HVt1g_Wm5JtalzA-5sA/edit
[2] https://github.com/ksdperera/ESB-Kerberos-Handler/tree/fixingIssues

Is it okay to get this JAR and host it somewhere in the docs so that people can download. wdyt?
We might have to do a quick smoke test.

**Comment by Nirothipan** [comment]
Shall we check the jar in https://docs.wso2.com/display/EI650/Applying+Security+to+an+API#ApplyingSecuritytoanAPI-UsingKerberostosecuretheRESTAPI
