### ISSUE TITLE
[Micro Integrator Dashboard] link the user store configuration doc 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/docs-ei#1734]
**Description:**
Doc: https://ei.docs.wso2.com/en/7.1.0/micro-integrator/administer-and-observe/working-with-monitoring-dashboard/

After or before '"Install and run the dashboard'' section we need to have the following document linked if a user needs to configure an external user store. 
https://ei.docs.wso2.com/en/7.1.0/micro-integrator/setup/user_stores/setting_up_a_userstore/

**Comment by nilminiwso2** [comment]
Added a note [1] to capture this information properly.

https://ei.docs.wso2.com/en/latest/micro-integrator/administer-and-observe/working-with-monitoring-dashboard/#setting-up-the-dashboard

Basically, the external user store is only required for user management tasks. Otherwise, the default file-based user store will suffice when using the dashboard.

Thanks!
