### ISSUE TITLE
Missing Configuration when setting up external jdbc user store. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/docs-ei#1736]
Doc: https://ei.docs.wso2.com/en/7.1.0/micro-integrator/setup/user_stores/setting_up_a_userstore/

The complete configuration as below. 

````
[[datasource]]
id = "WSO2_USER_DB"
url= "jdbc:mysql://10.110.5.230:3306/userdb"
username="root"
password="root"
driver="com.mysql.jdbc.Driver"
pool_options.maxActive=50
pool_options.maxWait = 60000
pool_options.testOnBorrow = true

[realm_manager]
data_source = "WSO2_USER_DB"

[user_store]
class = "org.wso2.micro.integrator.security.user.core.jdbc.JDBCUserStoreManager"
type = "database"

[internal_apis.file_user_store]
enable = false

````

It has been missed the **[realm_manager]** config.

**Comment by nilminiwso2** [comment]
We already had the following note for the 'id' description:

*If you replace 'WSO2CarbonDB' with a different id in the user DB configuration, you also need to list the id as a datasource under the <code>[realm_manager]</code> section in the <code>deployment.toml</code> file as shown below.
```toml
[realm_manager]
data_source = "new_id"
```
Otherwise the user store database id defaults to 'WSO2CarbonDB' in the realm manager configurations.*

Improved it further from this PR: https://github.com/wso2/docs-ei/pull/2309
