### ISSUE TITLE
Issues in Integration Usecases Tutorials

### ISSUE THREAD

**Issue by isuruuy429** [wso2/docs-ei#1748]
**Description:**
1. Further incorrect project are added in tutorials to download in the rest of the tutorials. (please revisit all the projects)
eg: MessageRouting - Simple Message services project. 

2. No pre-packaged projects for the following'.
https://ei.docs.wso2.com/en/7.1.0/micro-integrator/use-cases/tutorials/sending-a-simple-message-to-a-datasource/
https://ei.docs.wso2.com/en/7.1.0/micro-integrator/use-cases/tutorials/sending-a-simple-message-to-a-service/

3. Name the project as in the given tutorial name for users to understand easily.

**Comment by nilminiwso2** [comment]
1. The attached projects are correct - We have to use the project file from the previous tutorial in a the current tutorial.
2. The following two tutorials are starting points. Hence, we don't use a prepackaged project to start.
https://ei.docs.wso2.com/en/7.1.0/micro-integrator/use-cases/tutorials/sending-a-simple-message-to-a-datasource/
https://ei.docs.wso2.com/en/7.1.0/micro-integrator/use-cases/tutorials/sending-a-simple-message-to-a-service/
3. We will have to keep the project name as it is because it refers the previous tutorial and not the current one.

Will improve these instructions further during the tutorial testing. Thanks for the feedback!
